name: Sync issue/PR labels

on:
  push:
    branches:
      - master

    paths:
      - .github/labels.yml

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luisfi-dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Sync with GitHub Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
