name: Sync issue/PR labels

on:
  push:
    branches:
      - master

    paths:
      - .github/labels.yml

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luisfi-dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Sync with GitHub Labeler
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
